version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.7.3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_VHOST: ''
      RABBITMQ_DEFAULT_PASS: guest
